### PR TITLE
Msvc build

### PR DESCRIPTION
**Pull request by michael-kenzel**

### CODE REVIEW

**Comment by madmann91** [comment]
Should be fixed by recent commits by Stefan and me.

**Comment by michael-kenzel** [comment]
@madmann91 as far as I can tell, there are still a few headers missing (albeit it might happen to compile without those because they are pulled in by other stdlib headers by chance) in the current master, and the debug build will still be broken due to that #ifdef [here](https://github.com/AnyDSL/artic/pull/2/files#diff-7ec3c68a81efff79b6ca22ac1f1eabbaR17)

**Comment by madmann91** [comment]
That `#ifdef` was removed by Stefan ([here](https://github.com/AnyDSL/artic/commit/480f3554c4d18afae9092b6eede071355ffd5ecf)), and I've added the includes you gave me ([here](https://github.com/AnyDSL/artic/commit/53f3c7d9a31431b3b2dd0901ecfcc656c9b7493f)). Is there any other include I'm missing?

**Comment by michael-kenzel** [comment]
Oh, i must've missed that, sorry. I think that should be it then.

**Pull request closed without merging**
